---
- name: Transfer and execute a script.
  hosts: 10.238.23.78
  user: osadmin
#  become: yes
  tasks:
#     - name: Transfer the script
#       copy: src=/etc/ansible/rollback_rscd_agent.expect dest=/tmp mode=0777

     - name: Execute the script
       local_action: command ./tmp/rollback_rscd_agent.expect
